// generate-grammar.js (maize-429): writes syntaxes/mzasm.tmLanguage.json.
//
// The mnemonic alternation is DERIVED from docs/spec-v2/appendix-a-opcode-map.md by
// tests/appendix-a.js, never typed here. Run this after an appendix change:
//
//     node tests/generate-grammar.js          (from editors/vscode/)
//
// and commit the result. tests/grammar.test.js re-derives the same list on every test run and
// fails when the checked-in file and the appendix disagree, so a forgotten regeneration is
// caught rather than shipped. Running the generator is a convenience; the check is the
// guarantee.
//
// Every other keyword list below is hand-transcribed and cited, per the card's D-5 ruling. Each
// is at most 32 entries and each is stated as a closed list in one place:
//
//   - The 15 directive names: assembler.md "Statement grammar", the `directive_name`
//     production, mirrored by src/v2/mzasm_lexer.cpp's kDirectiveNames.
//   - The 4 section kinds: assembler.md "Statement grammar", the `section_kind` production.
//   - The 32 register aliases: src/v2/mzasm_lexer.cpp's kRegisterAliases table, which is
//     abi.md "Register roles" in full, including the three architectural aliases.

'use strict';

const fs = require('fs');
const path = require('path');
const { parseAppendix } = require('./appendix-a.js');

const ROOT = path.resolve(__dirname, '..');
const APPENDIX = path.resolve(ROOT, '..', '..', 'docs', 'spec-v2', 'appendix-a-opcode-map.md');
const OUTPUT = path.join(ROOT, 'syntaxes', 'mzasm.tmLanguage.json');

// assembler.md "Statement grammar", `directive_name`. Fifteen names, lowercase, no sigil.
const DIRECTIVES = [
    'section', 'origin', 'align',
    'data_byte', 'data_quarter_word', 'data_half_word', 'data_word',
    'data_string', 'data_string_zero', 'data_fill',
    'reserve', 'constant', 'global', 'extern', 'include',
];

// assembler.md "Statement grammar", `section_kind`.
const SECTION_KINDS = ['code', 'rodata', 'data', 'bss'];

// src/v2/mzasm_lexer.cpp kRegisterAliases, in register-number order. abi.md "Register roles"
// in full, with the three architectural aliases (zero = r0, sp = r30, ra = r31) in the same
// table so no second list can disagree with it.
const REGISTER_ALIASES = [
    'zero', 'tp', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7',
    't0', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9',
    's0', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8',
    'fp', 'sp', 'ra',
];

/* Escape a literal spelling for use inside a regex alternation. Mnemonics carry dots
   (`move.w`, `load.zb`, `extract.sh`), and an unescaped dot would match any character, so
   `load.zb` would also light up `loadXzb`. */
function escapeLiteral(text) {
    return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/* Build an alternation that matches the LONGEST spelling available at a position.
   Ordering is load-bearing rather than cosmetic. A backtracking engine takes the first
   alternative that matches, and `add` matches the first three characters of `add.h` with a
   word boundary after it (the dot is not a word character), so an alternation listing `add`
   first would paint `add` and leave `.h` bare. Sorting by descending length, then
   alphabetically for a stable file, makes the longer spelling win every such pair. */
function alternation(words) {
    return words
        .slice()
        .sort((a, b) => (b.length - a.length) || (a < b ? -1 : a > b ? 1 : 0))
        .map(escapeLiteral)
        .join('|');
}

// assembler.md "Numeric literals": two characters group digits, the comma and the back-tick.
// The underscore is NOT among them, because the underscore is an identifier character. The
// separator class is spelled once here so the three base rules cannot drift apart.
const SEPARATORS = ',`';

// assembler.md "Numeric literals": eight escapes and no others, shared by string and character
// literals. `\xHH` takes exactly two hexadecimal digits.
const ESCAPE = '\\\\(?:[\\\\"\'nrt0]|x[0-9A-Fa-f]{2})';

function buildGrammar(mnemonics) {
    const register = '(?:r(?:0|[1-9]|1[0-9]|2[0-9]|3[01])|' + alternation(REGISTER_ALIASES) + ')';

    return {
        $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
        name: 'Maize',
        scopeName: 'source.mzasm',

        // GENERATED FILE. Edit tests/generate-grammar.js and rerun it; do not edit this file
        // by hand. The mnemonic alternation is derived from
        // docs/spec-v2/appendix-a-opcode-map.md and is verified against it by
        // tests/grammar.test.js on every test run.
        //
        // No rule below carries a (?i) flag. assembler.md "Lexical structure": "Case matters
        // everywhere. Mnemonics, directive names, register names, and the width and format
        // suffixes are lowercase", so `MOVE` and `Load` are the names of nothing and must not
        // be painted as though they were.
        patterns: [
            { include: '#comment' },
            { include: '#string' },
            { include: '#character' },
            { include: '#label-declaration' },
            { include: '#directive' },
            { include: '#section-kind' },
            { include: '#register' },
            { include: '#mnemonic' },
            { include: '#here' },
            { include: '#hex-literal' },
            { include: '#dec-literal' },
            { include: '#bin-literal' },
            { include: '#address-operator' },
            { include: '#operator' },
            { include: '#parens' },
        ],

        repository: {
            // assembler.md "Lexical structure": a semicolon begins a comment that runs to the
            // end of the line. There is no block comment.
            comment: {
                match: ';.*$',
                name: 'comment.line.semicolon.mzasm',
            },

            // assembler.md "Lexical structure": a run of characters between straight double
            // quotes.
            string: {
                begin: '"',
                end: '"|$',
                name: 'string.quoted.double.mzasm',
                patterns: [
                    { match: ESCAPE, name: 'constant.character.escape.mzasm' },
                    // assembler.md "Numeric literals": "An unrecognized escape is a diagnostic
                    // rather than the escaped character." A blanket \\. catch-all cannot tell
                    // \n from \z, so the two cases are separate rules and the second says
                    // plainly that the source is wrong.
                    { match: '\\\\.', name: 'invalid.illegal.escape.mzasm' },
                ],
            },

            // assembler.md "Lexical structure": one character between straight single quotes.
            // v1 had no such token at all.
            character: {
                begin: "'",
                end: "'|$",
                name: 'string.quoted.single.mzasm',
                patterns: [
                    { match: ESCAPE, name: 'constant.character.escape.mzasm' },
                    { match: '\\\\.', name: 'invalid.illegal.escape.mzasm' },
                ],
            },

            // assembler.md "Symbols": an identifier followed by a colon on a line of its own.
            // v2 has no LABEL directive, so this is the only label declaration form.
            'label-declaration': {
                match: '^\\s*([A-Za-z_][A-Za-z0-9_]*)(:)',
                captures: {
                    1: { name: 'entity.name.label.mzasm' },
                    2: { name: 'punctuation.separator.label.mzasm' },
                },
            },

            directive: {
                match: '\\b(?:' + alternation(DIRECTIVES) + ')\\b',
                name: 'keyword.control.directive.mzasm',
            },

            'section-kind': {
                match: '\\b(?:' + alternation(SECTION_KINDS) + ')\\b',
                name: 'constant.language.section-kind.mzasm',
            },

            // assembler.md "Registers, aliases, and slices". The number carries no leading
            // zero and stops at 31, so `r5` is the register while `r05` and `r32` are
            // diagnostics and are left unpainted. The alternation enumerates the shapes a
            // legal register number takes rather than bounding the digit COUNT: a count bound
            // like [1-9][0-9]? rejects three digits by coincidence and still accepts r32.
            //
            // The optional slice tail is anchored to this rule specifically, and never to a
            // bare identifier, because the dot is not in the identifier alphabet: a slice is
            // the only construct in v2 that puts a dot after a name, so `foo.b5` is not
            // source this grammar should paint as though it were legal.
            register: {
                match: '\\b' + register + '\\b(?:(\\.)(b[0-7]|q[0-3]|h[01])\\b)?',
                name: 'variable.language.register.mzasm',
                captures: {
                    1: { name: 'punctuation.separator.slice.mzasm' },
                    2: { name: 'variable.language.slice.mzasm' },
                },
            },

            // GENERATED: derived from appendix A's Assigned rows. See the file header.
            mnemonic: {
                match: '\\b(?:' + alternation(mnemonics) + ')\\b',
                name: 'keyword.other.mnemonic.mzasm',
            },

            // assembler.md "Symbols": one identifier is reserved, and `here` names the address
            // of the first byte of the statement in which it appears.
            here: {
                match: '\\bhere\\b',
                name: 'constant.language.here.mzasm',
            },

            // assembler.md "Numeric literals": every literal names its base with a marker, the
            // sign FOLLOWS the marker, and a separator may sit between two digits but never
            // straight after the marker, straight after the sign, or at the end.
            //
            // A bare digit run carries no marker and is matched by none of the three rules
            // below, which is the whole point of the mandatory-base rule: `10` renders as
            // unstyled text rather than as a number whose base a reader would have to guess.
            'hex-literal': {
                match: '\\$[+-]?[0-9A-Fa-f](?:[' + SEPARATORS + ']?[0-9A-Fa-f])*',
                name: 'constant.numeric.hex.mzasm',
            },
            'dec-literal': {
                match: '#[+-]?[0-9](?:[' + SEPARATORS + ']?[0-9])*',
                name: 'constant.numeric.decimal.mzasm',
            },
            'bin-literal': {
                match: '%[+-]?[01](?:[' + SEPARATORS + ']?[01])*',
                name: 'constant.numeric.binary.mzasm',
            },

            // assembler.md "Statement grammar", the `memory` production: every memory operand
            // carries the @ sigil.
            'address-operator': {
                match: '@',
                name: 'keyword.operator.address.mzasm',
            },

            // assembler.md "Expressions". The % character is the binary base marker and is
            // deliberately absent here: it has no second meaning as a remainder operator.
            operator: {
                match: '<<|>>|[+\\-*/&|^~]',
                name: 'keyword.operator.arithmetic.mzasm',
            },
            parens: {
                match: '[()]',
                name: 'punctuation.parens.mzasm',
            },
        },
    };
}

function main() {
    const parsed = parseAppendix(APPENDIX);

    if (parsed.errors.length > 0) {
        console.error('Refusing to generate: the appendix parse reported problems.');
        for (const e of parsed.errors) {
            console.error('  ' + e);
        }
        process.exit(1);
    }

    const grammar = buildGrammar(parsed.mnemonics);
    fs.writeFileSync(OUTPUT, JSON.stringify(grammar, null, 4) + '\n', 'utf8');

    console.log('wrote ' + path.relative(ROOT, OUTPUT) + ' with ' + parsed.mnemonics.length +
        ' mnemonic spellings from ' + parsed.assignedRows + ' assigned opcodes');
}

module.exports = { buildGrammar, DIRECTIVES, SECTION_KINDS, REGISTER_ALIASES, APPENDIX, OUTPUT };

if (require.main === module) {
    main();
}
